### ISSUE TITLE
808服务端怎么获取设备的IP

### ISSUE THREAD

**Issue by jifeilong9** [SmallChi/JT808Gateway#1]
你好，808服务端能获取到设备的ip吗？

**Comment by SmallChi** [comment]
可以的,网关Session有记录设备的通道信息

**Comment by SmallChi** [comment]
也可以通过webapi接口获取。
[获取tcp会话服务](https://github.com/SmallChi/JT808DotNetty/tree/master/api#tcp_session)

**Comment by jifeilong9** [comment]
已解决感谢大佬！

**Comment by SmallChi** [comment]
不是大佬，只是搬砖的
