### ISSUE TITLE
Pipeline与DotNetty版本性能方面有差异吗？

### ISSUE THREAD

**Issue by 491134648** [SmallChi/JT808Gateway#10]
Pipeline  DotNetty性能方面有差异吗？

**Comment by SmallChi** [comment]
有点吧，虽然DotNetty是稳定的，但是更新好慢呐，建议用pipeline吧，简单又好用，又没有多少代码量。😄

**Comment by 491134648** [comment]
好吧，群主回复的这么快？有类似dotnetty下LengthFieldBasedFrameDecoder的解码器实现吗？

**Comment by SmallChi** [comment]
[参考新能源协议](https://github.com/SmallChi/JTNewEnergyDotNetty/blob/master/doc/jtne_tcp.md)
