### ISSUE TITLE
能否增加设备自定义协议处理方式？

### ISSUE THREAD

**Issue by zuohuaijun** [SmallChi/JT808Gateway#12]
对于某些GPS设备发送的非808协议数据用该网关怎么处理呢？网关可以改造么，谢谢

**Comment by SmallChi** [comment]
额，这个又不是一个通用的设备网关处理程序，这个网关的最初的定位就是基于808协议的，你要处理非808的协议那肯定不行呀，你可以自己改造呀，但是感觉没有必要呀，非国标就用非国标的网关接入就好，干嘛还要混在一起呢，但是怎么都有这种需求呢╮(╯▽╰)╭。

**Comment by zuohuaijun** [comment]
1、非国标网关有推荐么？谢谢
2、自己写个非国标的协议接收程序转成808给转发咱网关，可行？

**Comment by SmallChi** [comment]
用[SuperSocket](https://github.com/kerryjiang/SuperSocket)这个就是通用的了，什么数据都能接😁

**Comment by SmallChi** [comment]
竟然你都接收到非国标的协议，直接处理数据就好了，干嘛还要转成808的呢。

**Comment by raieoncc** [comment]
...国内有一家合肥的 他的datalink sdk支持多种协议 例如国内博实结的协议 你可以咨询一下&nbsp;

--------------原始邮件--------------
发件人："SmallChi(Koike) "<notifications@github.com&gt;;
发送时间：2020年4月26日(星期天) 凌晨0:16
收件人："SmallChi/JT808Gateway" <JT808Gateway@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：Re: [SmallChi/JT808Gateway] 能否增加设备自定义协议处理方式？ (#12)
-----------------------------------

 

 
用SuperSocket这个就是通用的了，什么数据都能接

**Comment by zuohuaijun** [comment]
因为咱这个808网关附带一些其他功能啊，比如各种服务、会话通知、大并发等

**Comment by zuohuaijun** [comment]
还有就是对接其他平台数据时，自己得主动去间隔拉取处理，通用被动接收也有点局限

**Comment by SmallChi** [comment]
> 
> ...国内有一家合肥的 他的datalink sdk支持多种协议 例如国内博实结的协议 你可以咨询一下&nbsp;
> […](#)
> --------------原始邮件-------------- 发件人："SmallChi(Koike) "<notifications@github.com&gt;; 发送时间：2020年4月26日(星期天) 凌晨0:16 收件人："SmallChi/JT808Gateway" <JT808Gateway@noreply.github.com&gt;; 抄送："Subscribed "<subscribed@noreply.github.com&gt;; 主题：Re: [SmallChi/JT808Gateway] 能否增加设备自定义协议处理方式？ (#12) ----------------------------------- 用SuperSocket这个就是通用的了，什么数据都能接 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

博实结的协议不是808的还是私有的吗？

**Comment by SmallChi** [comment]
你们这些大兄弟，这个毕竟适用808的就好了，你要兼容多协议的，不是不能做，只是不想重复造轮子，可以用[SuperSocket](https://github.com/kerryjiang/SuperSocket)这个也很好用呀。

**Comment by raieoncc** [comment]
作者老哥不好意思，我回复错了，我上面是想回复给题主的，不小心回复错了😂 ，感谢老哥的共享，我最近想用老哥的网管给trackcar增加jt808协议
-----------------------------------

 

 
你们这些大兄弟，这个毕竟适用808的就好了，你要兼容多协议的，不是不能做，只是不想重复造轮子，可以用SuperSocket这个也很好用呀。

**Comment by SmallChi** [comment]
😳😳这么迟才休息。。

**Comment by yedajiang44** [comment]
@zuohuaijun [DotNetty多协议实现思路](https://github.com/SmallChi/JT808Gateway/issues/11#issuecomment-727687417)
