### ISSUE TITLE
IJT808MsgConsumer等接口OnMessage的元组参数问题

### ISSUE THREAD

**Issue by nirdino** [SmallChi/JT808Gateway#14]
不太明白 这些接口里面为什么使用元组作为参数而不是强类型，目前遇到一些麻烦。在扩展RabbitMQ作为中间件时，想统一管理同进程中的订阅及分发调用，如果是强类型可以用泛型处理各个接口间不同的参数，但是目前您源码采用的是元组参数，动态调用不好处理，您设计时使用元组参数有什么特殊的原因吗？
调用的部分：
![image](https://user-images.githubusercontent.com/5669487/94220843-74aec780-ff1c-11ea-91e3-4c97dd984c41.png)
几个订阅的接口
![image](https://user-images.githubusercontent.com/5669487/94220945-bd668080-ff1c-11ea-8475-ed56b5145838.png)
![image](https://user-images.githubusercontent.com/5669487/94220979-c9524280-ff1c-11ea-8740-b06c1821679d.png)
![image](https://user-images.githubusercontent.com/5669487/94220996-d40cd780-ff1c-11ea-8f42-0e41de755ac9.png)
JT808MsgConsumer的RabbitMQ实现部分
![image](https://user-images.githubusercontent.com/5669487/94221180-22ba7180-ff1d-11ea-89e2-7d8e372a8a33.png)

**Comment by nirdino** [comment]
找到解决办法了，不用改您的源码，谢谢

**Comment by SmallChi** [comment]
没有想那么多😩，感觉没有必要统一管理吧，每个消息有每个消息该做的事情，为啥要统一管理(⊙o⊙)。
