### ISSUE TITLE
有单独控制网关的start,stop功能吗

### ISSUE THREAD

**Issue by dodu2014** [SmallChi/JT808Gateway#17]
对于启动已配置好的端口的监听服务, 有单独控制器启动,暂停,结束的功能吗?
比如想集成到windows服务中运行, 在服务启动停止的时候对服务进行控制

**Comment by SmallChi** [comment]
大兄弟，那干嘛不直接控制HostBuilder出来的Hosting的启动和停止。

**Comment by dodu2014** [comment]
有没有考虑集成 worker services 这个也是跨平台的, 方便部署成为 windows服务或 linux守护进程

**Comment by SmallChi** [comment]
本身用的就是worker services的方式搞的呀。
