### ISSUE TITLE
StatusFlag  哪个状态是点火 哪个是熄火 

### ISSUE THREAD

**Issue by 344089386** [SmallChi/JT808Gateway#19]
我看了StatusFlag 基本都是0-3，提示是参考 JT808.Protocol.Enums.JT808Status ，
但是JT808Status的状态数据有点对不上啊？
![image](https://user-images.githubusercontent.com/22017199/122005732-91f82e80-cde8-11eb-80e7-e6085533ee44.png)
是在JT808MessageHandlerImpl  接收消息时取到的数据。

**Comment by SmallChi** [comment]
点火和熄火就是acc啊 (3 & 1)==1  1就是点火，0就是熄火。

**Comment by 344089386** [comment]
好的。我知道了 谢谢
