### ISSUE TITLE
运行JT808.Gateway.SimpleServer报错，不能连接127.0.0.1:20000

### ISSUE THREAD

**Issue by horsewww** [SmallChi/JT808Gateway#20]
编译完毕后，运行 JT808.Gateway.SimpleServer.exe 时出现下面的错误：
      **fail: JT808.Gateway.Transmit.JT808TransmitService[0]
      该终端all已尝试未连接上该服务器127.0.0.1:20000
      System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。**

这个监听20000端口的是哪个程序？怎么启动？

**Comment by SmallChi** [comment]
这个报错可以忽略，不影响，是转发设备消息到其他808网关，没有就配置文件注释掉就好了。
