### ISSUE TITLE
通过WebApi接口UnificationSend向设备发送消息后，拿不到设备返回的消息

### ISSUE THREAD

**Issue by horsewww** [SmallChi/JT808Gateway#21]
Q：通过WebApi接口UnificationSend向设备发送消息后，返回值只指明了是否发送成功，怎么取回设备返回的消息呢？比如发送0x8801后，设备返回0x0805,客户端怎么能拿到这个0x0805消息呢？

**Comment by SmallChi** [comment]
直接在网关或者消息队列里面取回0x0805的数据就好了。
