### ISSUE TITLE
GPS 设备超过2台，Channel 会频繁断开，倒置GPS设备重新注册 、鉴权.

### ISSUE THREAD

**Issue by whywhy898** [SmallChi/JT808Gateway#23]
你好作者，我用了你部分代码监听GPS设备（DotNetty TCP协议）,一台设备接入的时候正常接收信息，但是当2台以上GPS 设备通讯的时候 就会出现DotNetty 主动断开Channel 的情况，这时候GPS 设备又会重新连接（重新注册、鉴权）。 这种情况会频繁出现。  
我通过日志看到是先走了  CloseAsync函数 （您在注释中说是 server端主动断开）。想请您看看我的代码帮我分析一下问题（有偿）。
WX号：15141173250. 希望得到你的帮助。

**Comment by SmallChi** [comment]
已解决。
