### ISSUE TITLE
SocketOptionName.NoDelay   设置  True 的时候 在Docker  运行会报错

### ISSUE THREAD

**Issue by onlyleida** [SmallChi/JT808Gateway#28]
Unhandled exception. System.Net.Sockets.SocketException (13): Permission denied

**Comment by onlyleida** [comment]
把代码  

server.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.NoDelay, true);


改成  

server.NoDelay = true;  


就没问题了

**Comment by SmallChi** [comment]
@yedajiang44 docker的有时间试下哈。

**Comment by yedajiang44** [comment]
@leida1983 有尝试将容器设置为 privileged 吗？

**Comment by onlyleida** [comment]
> @leida1983 有尝试将容器设置为 privileged 吗？

谢谢  解决
