### ISSUE TITLE
接收808转发数据问题

### ISSUE THREAD

**Issue by ahern2012** [SmallChi/JT808Gateway#30]
大佬，接收平台方转发数据这里貌似有坑，目前有两种情况：1、连接正常情况下，对方IP端口不变，断开连接后调用item.ReceiveTimeout.Cancel()无效，超过10分钟的会话仍然存在，必须调用SessionManager.RemoveByTerminalPhoneNo方法才能移除该会话，不调用则必须重启服务，否则无法再次上线，重启服务之后也不能立即上线，需要最长10分钟才能上线。
2、对方IP不变端口一直在变，会话中存在多条该终端号记录，其中包含相同的IP端口数据，也有不同的端口。每台设备平均每10秒钟打印一条JT808SessionOnline日志。

JT808SessionManager.TerminalPhoneNoSessions数量为1500，JT808SessionManager.Sessions数量超过10万，不重启服务会话数量会一直增长，内存也随之不断增长。

**Comment by SmallChi** [comment]
1.新版应该是解决了的
2.要看看具体数据是怎么对应的
@yedajiang44 你方便的时候帮看下1的问题，好像你上次解决了不是？

**Comment by ahern2012** [comment]
JT808.Gateway用的就是最新的版本

**Comment by SmallChi** [comment]
@yedajiang44 老6没有提交。O(∩_∩)O哈哈~

**Comment by ahern2012** [comment]
![1717468241597](https://github.com/SmallChi/JT808Gateway/assets/46569941/5dc67edb-f381-4db9-a8d8-7689239f4cc9)
这是第二种转发方式其中一台终端的错误日志，对方平台频繁的断开、连接导致FillPipeAsync，ReadPipeAsync读写报异常，SessionManager.RemoveBySessionId(session.SessionID)并未正确执行，所以socket连接会话才会不断增长？

**Comment by yedajiang44** [comment]
> ![1717468241597](https://private-user-images.githubusercontent.com/46569941/336284399-5dc67edb-f381-4db9-a8d8-7689239f4cc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzAxNDQsIm5iZiI6MTcxNzQ2OTg0NCwicGF0aCI6Ii80NjU2OTk0MS8zMzYyODQzOTktNWRjNjdlZGItZjM4MS00ZGI5LWE4ZDgtNzY4OTIzOWY0Y2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAyNTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYzYwOWQ4YmMwMDY0NmRkZjA4YTkxYzczZGEyNTJhMWMwZmZiNzRmMjUzZDJiNWM3NTNjZDcyYzQ3ZTAyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-lyOogfl4rIwEzBBzmw3Xrz_y-0DXG3LxOuI7ZgDG0k) 这是第二种转发方式其中一台终端的错误日志，对方平台频繁的断开、连接导致FillPipeAsync，ReadPipeAsync读写报异常，SessionManager.RemoveBySessionId(session.SessionID)并未正确执行，所以socket连接会话才会不断增长？

拉下代码，你的这个问题之前没提交，测着测着就忘了，另外`JT808SessionManager.Sessions`连接数多是另有其因，需要酌情考虑下怎么合理的处理。或者有什么想法直接提pr

**Comment by ahern2012** [comment]
好的，谢谢大佬！
