### ISSUE TITLE
容器内运行必须加特权会带来潜在的安全性问题

### ISSUE THREAD

**Issue by liang-junwei** [SmallChi/JT808Gateway#31]
我尝试在容器中运行时，发现必须使用 root 并且 要使用参数--privileged=true，我查了一些资料问题指向了 Raw socket使用问题，这会给容器带来潜在的安全问题，能否有办法避免？

**Comment by SmallChi** [comment]
@yedajiang44 帮看看，容器很少用。

**Comment by yedajiang44** [comment]
@liang-junwei `dockerfile`发下
