### ISSUE TITLE
请问有支持JTT 808 2019版本的计划吗

### ISSUE THREAD

**Issue by liaoyongxiong** [SmallChi/JT808Gateway#4]
部标2019版本已经发布，请问后续是否有支持2019版本的计划？
[JTT 808-2019.PDF](https://github.com/SmallChi/JT808DotNetty/files/3867768/JTT.808-2019.PDF)

**Comment by liaoyongxiong** [comment]
[JTT 808-2019.PDF](https://github.com/SmallChi/JT808DotNetty/files/3867775/JTT.808-2019.PDF)

**Comment by SmallChi** [comment]
感谢提供文档，会支持的，但是现在用2019版本的应该比较少吧

**Comment by liaoyongxiong** [comment]
估计明年过检会做强制要求，附809文档一份
[JTT 809-2019.PDF](https://github.com/SmallChi/JT808DotNetty/files/3869966/JTT.809-2019.PDF)

**Comment by SmallChi** [comment]
这个808文档不是最新的吧？这个文档好坑呐  0x0100制造商ID是11个字节但是0x0107和0x8108又变成5个字节。。。

**Comment by liaoyongxiong** [comment]
是最新的

**Comment by SmallChi** [comment]
2.3.0版本已经兼容了2019版本的808协议
[参考1](https://github.com/SmallChi/JT808/blob/master/src/JT808.Protocol.Test/Simples/Demo7.cs)
[参考2](https://github.com/SmallChi/JT808DotNetty/tree/master/simples/JT808.DotNetty.SimpleClient)
