### ISSUE TITLE
大神，这个包在源码中没找到，JT808.DotNetty.Transmit

### ISSUE THREAD

**Issue by AchaInChina** [SmallChi/JT808Gateway#5]
大神，JT808.DotNetty.Transmit 这个不开源吗，我在源码中没找到。

**Comment by SmallChi** [comment]
有的呀，都是开源的https://github.com/SmallChi/JT808DotNetty/tree/master/src/JT808.DotNetty.Services/JT808.DotNetty.Transmit

**Comment by AchaInChina** [comment]
我找到了，没更新代码。
