### ISSUE TITLE
运行找不到appsettings.json文件

### ISSUE THREAD

**Issue by mudalu** [SmallChi/JT808Gateway#6]
运行找不到appsettings.json文件
![image](https://user-images.githubusercontent.com/1161752/70368719-6c33c480-18e9-11ea-8b43-1c31279cd16e.png)

**Comment by SmallChi** [comment]
大兄弟，是哪个项目下面的。图片看不到。

**Comment by SmallChi** [comment]
重新拉取下就好了，不是最新的吧

**Comment by waleswood** [comment]
好多都没有哇，比如 JT808.DotNetty.MsgLogging.Test 等各种 Test项目

**Comment by waterliu99** [comment]
> 好多都没有哇，比如 JT808.DotNetty.MsgLogging.Test 等各种 Test项目

已添加配置文件
