### ISSUE TITLE
HTML5中使用websocket怎么使用此网关进行数据同步

### ISSUE THREAD

**Issue by zuohuaijun** [SmallChi/JT808Gateway#9]
1、gps数据通过此网关处理后，怎么通过websocket将接收到的GPS位置数据广播到所有html5页面中，h5中通过websocket获取位置数据后立刻更新位置。
2、此网关服务实例怎么扩展自定义接收到的消息呢？不是标准的808协议

**Comment by SmallChi** [comment]
1.一般通过订阅kafka消费者的方式，当设备有数据上来的时候，就可以通知到该消费者然后在推送到前端至于前端如何接收，要看自己的业务场景；
2.网关只支持标准808消息协议，不支持私有协议。

**Comment by zuohuaijun** [comment]
老大，前端HTML页面怎么通过咱这个网关订阅消息（订阅所有GPS数据或者指定其中一台GPS数据）？有这方面的示例么？咱这个网关还有其他具体使用示例么？谢谢
还有simples中的JT808.DotNetty服务端事例怎么扩展消息订阅、websocket服务呢？谢谢

**Comment by SmallChi** [comment]
额，可以先去了解下[kafka](https://github.com/confluentinc/confluent-kafka-dotnet)，订阅的都是全部的设备数据，至于推送的话肯定要结合平台的使用场景，不可能每个用户都可以看到所有车辆，肯定要根据用户进行分组推送。至于demo的话，目前只有这些简单的，还需要时间不断的增加完善。

**Comment by SmallChi** [comment]
[参考Demo](https://github.com/SmallChi/JT808Gateway/tree/master/simples/JT808.Gateway.SimpleQueueNotification)
